#!/usr/bin/env ruby
if File.exist?('fresh')
  then
  puts 'Application updated..'
  processor, platform, *rest = RUBY_PLATFORM.split("-")
  unless platform == 'mswin32'
  `rake db:migrate`
  else
    system('cmd.exe /c ruby db:migrate')
  end
  unless File.exist?('config/prefs.yml') 
    then
    f=File.open('config/prefs.yml','w')
    a=['---',':pref:','  cmd: "echo "','  logs: 1']
    a.each do |l| f.puts l end
    f.close
  end
   File.delete('fresh')
else
  puts 'Il ne peux plus rien nous arriver d\'affreux maintenant'
end
unless platform == 'mswin32'
  exec "script/server"+" "+ARGV.to_s
else
  system("cmd.exe /c ruby script/server"+" "+ARGV.to_s)
end